[tool.poetry]
name = "reliesl"
version = "0.1.0"
description = "Reliesl is a tool for automatic release managment using the Gitlab CI."
authors = ["Benedikt Wiberg <benedikt@luminovo.ai>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/luminovo/public/reliesl"
repository = "https://gitlab.com/luminovo/public/reliesl"
keywords = ["gitlab", "release", "continuous", "integration"]
classifiers = ["Environment :: Console"]

include = ["LICENSE"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
semver = "^2.8"
toml = "^0.10.0"
click = "^7.0"

[tool.poetry.scripts]
reliesl = "reliesl.cli:main"

[tool.poetry.dev-dependencies]
pytest = "^3.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
