[tool.poetry]
name = "cimsim"
version = "1.2.0"
description = ""
authors = ["Airat <airat_vi@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.5"
requests = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
