[tool.poetry]
name = "gtk-datetime-popover"
version = "2.0.0"
description = "A Gtk Popover widget for handling dates and times"
authors = ["BeatLink <beatlink@protonmail.com>"]
license = "GPL-3.0+"

packages = [{include = "datetime_popover"}]

[tool.poetry.dependencies]
python = "^3.6"
pygobject = "^3.32.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
